runtime: nodejs
env: flex
env_variables:
  SQL_USER: root
  SQL_PASSWORD: ODds37ffCwI4pbvC
  SQL_DATABASE: prod
  INSTANCE_CONNECTION_NAME: hourinetwork:europe-west1:mysql

beta_settings:
  cloud_sql_instances: hourinetwork:europe-west1:mysql

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
builtins:
- appstats: on