runtime: nodejs
env: flex
env_variables:
  SQL_USER: default
  SQL_PASSWORD: default
  SQL_DATABASE: production
  INSTANCE_CONNECTION_NAME: hourinetwork:europe-west1:production

beta_settings:
  cloud_sql_instances: hourinetwork:europe-west1:production

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
builtins:
- appstats: on