runtime: nodejs
env: flex
env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: v6ByojC18AgysnAf
  SQL_DATABASE: postgres
  INSTANCE_CONNECTION_NAME: hourinetwork:europe-west1:test

beta_settings:
  cloud_sql_instances: hourinetwork:europe-west1:test

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
builtins:
- appstats: on