version: 2
jobs:
  build:    
    docker:
      - image: circleci/node:8.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm --version && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  unit:
    docker:
      - image: circleci/node:8.5.0 
    steps:
      - checkout
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Unit Test
          command: npm run unit
      # - run:
      #     name: Generate code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit:
          requires:
            - build
      - e2e:
          requires:
            - build
            - unit
          filters:
            branches:
              only: master